behaviors:
  PlayerBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
    network_settings:
      hidden_units: 32
      num_layers: 1
    max_steps: 500
# 작동
# conda activate py38_mlagents
# mlagents-learn C:\project\MSRebirth\Assets\ML\playerData.yaml --run-id=ML_0526_10
# mlagents-learn C:\project\MSRebirth\Assets\ML\playerData.yaml --run-id=ML_0525_1 --initialize-from=ML_0524_14
# --initialize-from=ML
# --resume
# tensorboard --logdir results