behaviors:
  PlayerBehavior:
    trainer_type: ppo
    hyperparameters:
      batch_size: 10
    network_settings:
      hidden_units: 32
      num_layers: 1
    max_steps: 500
# 작동
# conda activate py38_mlagents
# C:\project\MSRebirth\Assets\ML\playerData.yaml --run-id=ML1
# tensorboard --logdir results